[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2021"
version = "0.0.1"
authors = ["clabby"]

[workspace.dependencies]
anyhow = "1.0.79"
tokio = { version = "1.35.1", features = ["macros"] }
async-trait = "0.1.77"
alloy-primitives = "0.6.0"
