[package]
name = "durin-primitives"
description = "Primitive types for Durin."
authors = ["clabby"]

version.workspace = true

[dependencies]
alloy-primitives = { version = "0.4.2" }
anyhow = "1.0.75"
